### ISSUE TITLE
 DARK HERESY 2ND EDITION - TODO LIST

### ISSUE THREAD

**Issue by medricr** [medricr/datahammer#1]
# Armoury
- [ ] Weapon stat lines
- [ ] Weapon Special Qualities
- [ ] Ammunition Stats & Descriptions
- [ ] Weapon Attachment Stats & Descriptions
- [ ] Cybernetics Stats & Descriptions
- [ ] Armour stat lines
- [ ] Vehicle Stats & Descriptions
- [ ] Mount Stats & Descriptions

# Talents, Traits, and Skills
- [ ] Talent Descriptions & Page Numbers
- [ ] Trait Descriptions & Page Numbers
- [ ] Skill Descriptions & Page Numbers

# Rule References
- [ ] Status Effect Descriptions & Page Numbers
- [ ] Psychic Powers Descriptions & Page Numbers
